### PR TITLE
Drop support for EOL Python 2.7-3.5

### PR DESCRIPTION
**Pull request by hugovk**
Replaces and closes https://github.com/sumerc/yappi/pull/145.

Python 2.7 to 3.7 are EOL and no longer receiving security updates.

image

https://devguide.python.org/versions/

This PR:

* removes them from the CI and updates GitHub Actions
* removes redundant code for those versions
* modernises Python syntax using https://github.com/asottile/pyupgrade
* fixes version comparisons to work with a hypothetical Python 4.0 (or 23.0 if CalVer is introduced)

### CODE REVIEW

**Comment by sumerc** [comment]
This is a beneficial PR. But there is significant amount of users using 3.6. While 2.7 dropped significantly, there are still some very old versions:

https://pypistats.org/packages/yappi

I would at least expect to see 3.6 supported.

**Comment by hugovk** [comment]
Hmm, that's strange. Looks like they're all coming from CentOS, for whatever reason.


```console
❯ pypinfo --days 1 --limit 20 --percent --markdown "yappi==1.4.0" system distro pyversion
Served from cache: False
Data processed: 28.68 MiB
Data billed: 29.00 MiB
Estimated cost: $0.01
```

| system_name | distro_name              | python_version | percent | download_count |
| ----------- | ------------------------ | -------------- | ------: | -------------: |
| Linux       | CentOS Linux             | 3.6            |  90.53% |         71,472 |
| Linux       | Debian GNU/Linux         | 3.7            |   3.07% |          2,427 |
| Linux       | Ubuntu                   | 3.7            |   1.74% |          1,377 |
| Linux       | Ubuntu                   | 3.10           |   1.19% |            939 |
| Linux       | Ubuntu                   | 3.11           |   0.70% |            551 |
| Linux       | Ubuntu                   | 3.8            |   0.61% |            480 |
| Linux       | Debian GNU/Linux         | 3.11           |   0.59% |            465 |
| Linux       | Debian GNU/Linux         | 3.10           |   0.47% |            370 |
| Linux       | Debian GNU/Linux         | 3.9            |   0.29% |            229 |
| Linux       | Ubuntu                   | 3.9            |   0.17% |            134 |
| Linux       | Debian GNU/Linux         | 2.7            |   0.09% |             69 |
| Linux       | CentOS Stream            | 3.9            |   0.08% |             67 |
| Linux       | CentOS Linux             | 3.9            |   0.08% |             63 |
| Linux       | Ubuntu                   | 2.7            |   0.08% |             60 |
| Linux       | Debian GNU/Linux         | 3.8            |   0.07% |             52 |
| Linux       | Alpine Linux             | 3.9            |   0.06% |             50 |
| Linux       | Red Hat Enterprise Linux | 3.9            |   0.05% |             39 |
| Windows     | None                     | 3.10           |   0.05% |             36 |
| Darwin      | macOS                    | 3.8            |   0.04% |             33 |
| Linux       | AlmaLinux                | 3.9            |   0.04% |             32 |
| Total       |                          |                |         |         78,945 |

If it was me, I'd still drop 3.6, but it's at least beneficial to drop 2.7-3.5, so I'll update the PR to keep EOL 3.6 and 3.7.

Do note however that GitHub Actions no longer supports 2.7 or 3.6, so we'll have to just cross our fingers that things keep working on 3.6 in the future...

**Comment by sumerc** [comment]
> Do note however that GitHub Actions no longer supports 2.7 or 3.6, so we'll have to just cross our fingers that things keep working on 3.6 in the future...

I agree and thanks!

**Comment by sumerc** [comment]
I am more than happy to finally use f-strings :)

**Comment by hugovk** [comment]
Thank you very much for Yappi, it's been a really useful tool!

**Pull request merged**
